### ISSUE TITLE
To-do before `v0.1`

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#477]
The things to do before releasing a `0.1` for xDEM are:

- [x]  #474 then update related documentation example to make them even more accessible,
- [x]  #275 without forgetting to copy the `Raster` API to help users,
- [x] Deal with all warnings in tests making `UserWarning` fail tests everywhere,
- [x] Write more useful error message that propose solutions.

Coregistration improvements can be left for a next minor version, as well as elevation point clouds, etc.
